# Generated by Django 5.0.6 on 2024-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_food_image_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('bar', 'bar'), ('snack', 'snack'), ('dessert', 'dessert'), ('proper_nutrition', 'proper_nutrition')], default='breakfast', max_length=100),
        ),
    ]
