# Generated by Django 5.0.6 on 2024-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Courier', 'Courier'), ('Barmen', 'Barmen'), ('Waitress', 'Waitress'), ('Customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
