# Generated by Django 5.0.6 on 2024-06-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Courier', 'Courier'), ('Barmen', 'Barmen'), ('Waitress', 'Waitress'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
