# Generated by Django 5.0.6 on 2024-08-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
