# Generated by Django 5.0.6 on 2024-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Cook', 'Cook'), ('Seller', 'Seller'), ('Courier', 'Courier'), ('Barmen', 'Barmen'), ('Waitress', 'Waitress'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
