version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_DB=ucafe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=856329471Jas
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    command: gunicorn ucafe.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    expose:
      - 8000
    volumes:
      - static_files:/app/static
    depends_on:
      - db
      - redis
    restart: unless-stopped

  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 4000 ucafe.asgi:application
    container_name: daphne
    expose:
      - 4000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: unless-stopped


  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_files:/app/static
    depends_on:
      - web
    restart: unless-stopped

volumes:
  pgdata:
  static_files:
