# Generated by Django 5.0.6 on 2024-06-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
