# Generated by Django 5.0.6 on 2024-06-10 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pay_type', models.CharField(choices=[('cash', 'cash'), ('payme', 'payme'), ('click', 'click'), ('terminal', 'terminal')], default='cash', max_length=50)),
                ('order_type', models.CharField(choices=[('delivery', 'delivery'), ('with', 'with'), ('there', 'there')], default='there', max_length=50)),
                ('position', models.IntegerField(default=1)),
                ('full_price', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('delivering', 'Delivering'), ('completed', 'Completed')], default='processing', max_length=50)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.PositiveBigIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foods.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
