# Generated by Django 5.0.6 on 2024-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
