# Generated by Django 5.0.6 on 2024-06-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
