# Generated by Django 5.0.6 on 2024-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('on_road', 'On road'), ('delivered', 'Delivered')], default='waiting', max_length=50),
        ),
    ]
