# Generated by Django 5.0.6 on 2024-06-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lift',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='left', max_length=50),
        ),
    ]
