# Generated by Django 5.0.6 on 2024-06-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_basket_full_price_basket_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
