# Generated by Django 5.0.6 on 2024-08-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_delete_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_type',
        ),
        migrations.CreateModel(
            name='OrderPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('cash', 'cash'), ('payme', 'payme'), ('click', 'click'), ('terminal', 'terminal')], default='cash', max_length=50)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
