# Generated by Django 5.0.6 on 2024-08-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_pay_type_orderpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayments',
            old_name='amount',
            new_name='price',
        ),
    ]
