# Generated by Django 5.0.6 on 2024-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_amount_orderpayments_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
